import type { Lang } from "./site";

// Fixed page text (headings, buttons, labels) in English and Roman Urdu.
export const ui = {
  en: {
    nav: { services: "Services", about: "About", experience: "Experience", work: "Work", hire: "Freelance", contact: "Contact" },
    hireMe: "Hire me",
    menu: "Open menu",
    switchLang: { label: "Roman Urdu", href: "/ur" },
    available: "Available for freelance projects",
    eyebrow: "Digital Marketer · Web Developer · Lahore & Islamabad",
    headline: ["I grow businesses online with ", "SEO, ads", " and ", "websites that convert", "."],
    lead: (years: number) =>
      `I'm Rao Muneeb, a digital marketer and web developer with ${years}+ years of experience, including marketing agencies in Lahore and Islamabad. From websites and SEO to social media, Meta & Google Ads, graphic design and video editing, I handle it all in one place.`,
    consult: "Get a free consultation",
    seeWork: "See my work",
    servicesTitle: "Services",
    servicesLead: "Everything a business needs to be found online, stand out on social media and turn visitors into customers.",
    aboutTitle: "About me",
    about: (years: number) => [
      `For more than ${years} years I have worked with businesses as a freelancer and inside digital marketing agencies in Lahore and Islamabad, handling web development, SEO, social media, Meta and Google Ads, graphic design and video editing for clients in e-commerce, healthcare, construction, real estate and local services across Pakistan, the USA and the Gulf.`,
      "Because I do both marketing and development, the websites I build are fast, SEO-ready and set up with proper tracking from day one, and the campaigns I run are backed by creatives, videos and landing pages that actually convert.",
      "I also work with clients directly as a freelancer, so you get agency-level experience with the speed and personal attention of working with one person.",
    ],
    experienceTitle: "Experience",
    workTitle: "Websites I've built",
    workLead: "Live websites for clients in Pakistan, the USA, Europe, Saudi Arabia and the UAE. Click any project to visit the site.",
    visit: "Visit",
    screenshotAlt: "website homepage",
    reviewsTitle: "What clients say",
    hireTitle: "Hire me as a freelancer",
    hireLead: "Pick what fits your business. Every project starts with a free consultation and a clear quote.",
    popular: "Most popular",
    quote: "Get a quote",
    stepsTitle: "How we'll work together",
    faqTitle: "Frequently asked questions",
    contactTitle: "Let's grow your business",
    contactLead: "Tell me about your project and I'll get back to you within 24 hours.",
    whatsapp: "Chat on WhatsApp",
    orCall: "Or call",
    waMessage: "Hi Muneeb, I found your website and would like to discuss a project.",
    footer: "Freelance Digital Marketer & Web Developer, Lahore & Islamabad.",
    photoAlt: "Rao Muneeb, Digital Marketer & Web Developer in Lahore and Islamabad",
    iAm: "I'm a",
    roles: ["Web Developer", "SEO Expert", "Meta Ads Specialist", "Google Ads Expert", "Social Media Marketer", "Graphic Designer", "Video Editor"],
    badges: { years: "Years experience", sites: "Websites built", ads: "Meta & Google Ads" },
    brandsTitle: "Brands I've built for",
    filterAll: "All",
    showAll: "Show all projects",
    visitSite: "Visit website",
    ctaBandTitle: "Have a project in mind?",
    ctaBandText: "Let's talk about your website, ads or social media. The first consultation is free.",
    footerBio: "Freelance digital marketer and web developer helping businesses in Pakistan and abroad grow with websites, SEO, ads and creative content.",
    footerLinks: "Quick links",
    footerServices: "Services",
    footerContact: "Contact",
    location: "Bahria Town, Islamabad, Pakistan",
    rights: "All rights reserved.",
    backToTop: "Back to top",
  },
  ur: {
    nav: { services: "Services", about: "Mere Baare Mein", experience: "Tajurba", work: "Kaam", hire: "Freelance", contact: "Rabta" },
    hireMe: "Hire karein",
    menu: "Menu kholein",
    switchLang: { label: "English", href: "/" },
    available: "Freelance projects ke liye available",
    eyebrow: "Digital Marketer · Web Developer · Lahore aur Islamabad",
    headline: ["Main aapka business online grow karta hoon ", "SEO, ads", " aur ", "behtareen websites", " se."],
    lead: (years: number) =>
      `Main Rao Muneeb hoon, digital marketer aur web developer, ${years}+ saal ke tajurbe ke sath, jis mein Lahore aur Islamabad ki marketing agencies bhi shamil hain. Website aur SEO se le kar social media, Meta aur Google Ads, graphic design aur video editing tak, sab kuch ek hi jagah.`,
    consult: "Free consultation lein",
    seeWork: "Mera kaam dekhein",
    servicesTitle: "Services",
    servicesLead: "Wo sab kuch jo aapke business ko online nazar aane, social media par chha jaane aur visitors ko customers banane ke liye chahiye.",
    aboutTitle: "Mere baare mein",
    about: (years: number) => [
      `${years} saal se zyada arse se main freelancer ke taur par aur Lahore aur Islamabad ki digital marketing agencies mein kaam kar raha hoon. Pakistan, USA aur Gulf ke e-commerce, healthcare, construction, real estate aur local businesses ke liye web development, SEO, social media, Meta aur Google Ads, graphic design aur video editing karta hoon.`,
      "Kyunke main marketing aur development dono karta hoon, meri banayi websites fast, SEO-ready aur pehle din se tracking ke sath hoti hain, aur meri campaigns ke peeche aise creatives, videos aur landing pages hote hain jo waqai results dete hain.",
      "Main clients ke sath seedha freelancer ke taur par bhi kaam karta hoon, is liye aapko agency jaisa tajurba milta hai, magar ek hi banda aapke kaam par poori tawajjo deta hai.",
    ],
    experienceTitle: "Tajurba",
    workTitle: "Meri banayi hui websites",
    workLead: "Pakistan, USA, Europe, Saudi Arabia aur UAE ke clients ki live websites. Kisi bhi project par click karke website dekhein.",
    visit: "Dekhein",
    screenshotAlt: "website ka homepage",
    reviewsTitle: "Clients kya kehte hain",
    hireTitle: "Mujhe freelancer ke taur par hire karein",
    hireLead: "Jo aapke business ke liye behtar ho wo chunein. Har project free consultation aur saaf quote se shuru hota hai.",
    popular: "Sab se zyada pasand",
    quote: "Quote lein",
    stepsTitle: "Hum kaise kaam karenge",
    faqTitle: "Aksar puche jane wale sawal",
    contactTitle: "Aaiye aapka business grow karein",
    contactLead: "Apne project ke baare mein batayein, main 24 ghante mein jawab dunga.",
    whatsapp: "WhatsApp par baat karein",
    orCall: "Ya call karein",
    waMessage: "Assalam o Alaikum Muneeb, maine aapki website dekhi hai aur ek project ke baare mein baat karni hai.",
    footer: "Freelance Digital Marketer aur Web Developer, Lahore aur Islamabad.",
    photoAlt: "Rao Muneeb, Lahore aur Islamabad mein Digital Marketer aur Web Developer",
    iAm: "Main hoon",
    roles: ["Web Developer", "SEO Expert", "Meta Ads Specialist", "Google Ads Expert", "Social Media Marketer", "Graphic Designer", "Video Editor"],
    badges: { years: "Saal ka tajurba", sites: "Websites banayi", ads: "Meta aur Google Ads" },
    brandsTitle: "In brands ke liye kaam kiya",
    filterAll: "Sab",
    showAll: "Saare projects dekhein",
    visitSite: "Website dekhein",
    ctaBandTitle: "Koi project zehan mein hai?",
    ctaBandText: "Apni website, ads ya social media ke baare mein baat karein. Pehli consultation bilkul free hai.",
    footerBio: "Freelance digital marketer aur web developer jo Pakistan aur bahar ke businesses ko websites, SEO, ads aur creative content se grow karne mein madad karta hai.",
    footerLinks: "Links",
    footerServices: "Services",
    footerContact: "Rabta",
    location: "Bahria Town, Islamabad, Pakistan",
    rights: "Tamam huqooq mehfooz hain.",
    backToTop: "Upar jayein",
  },
} satisfies Record<Lang, unknown>;
